spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
    initialization-mode: always # ???
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
#      FAIL_ON_UNKNOWN_PROPERTIES: false

#    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
#    deserialization:
#      fail-on-ignored-properties: false
#      fail-on-unknown-properties: false

  #    default-property-inclusion: non_null
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
#    root: debug
    web: debug
    sql: info
    org.springframework.security: info
    org.hibernate.SQL: INFO
    com.sinhro.songturn.backend:
      service: debug
#    com.zaxxer.hikari: debug
#    org.springframework.jdbc: debug
#    java: trace
#    org.apache: trace


